import { Viewport } from 'next';
import './styles.css';
import { Raleway } from 'next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width'
}

const raleway = Raleway({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={raleway.className}>
      <body>{children}</body>
    </html>
  )
}
